### ISSUE TITLE
Importer le contenu depuis Joomla

### ISSUE THREAD

**Issue by editions-barzakh** [editions-barzakh/site#2]
Nous sommes dans l'attente d'un dumb des administrateurs, nous ferons suivre.

**Comment by npeltier** [comment]
@editions-barzakh (au fait pour s'adresser à quelqu'un, il faut aujouter @ puis quelqu'un, il recevra alors un mail), je vous assigne cette tâche dans la mesure ou le compte fourni (dridi) ne permet pas d'accéder à l'administration "bas-niveau" du site. Il doit exister des comptes plus "puissant". 
Pourriez vous demander à votre hébergeur:
- les paramètres de connexion à la base de donnée MySQL utilisée par votre site actuel
  OU
- un dump de cette base de données? (c'est à dire un gros fichier contenant tout le contenu).

**Comment by npeltier** [comment]
@editions-barzakh merci pour le contenu. Par contre je n'ai pas les images... y aurait-il un moyen de les récupérer?

**Comment by editions-barzakh** [comment]
@npeltier  Les listes des auteurs et des publications envoyées sont complètes. Merci. En ce qui concerne les images, elles sont toutes réunies dans joomla :  dans le dossier intitulé "Images site" dans "Gestion des médias" 
J'ignore s'il y a un moyen de télécharger tout le dossier.  sinon, je peux reconstituer des dossiers images à partir de la liste des auteurs et des publications, mais ça mettra un peu plus de temps.

**Comment by npeltier** [comment]
@editions-barzakh ok, j'ai pu récupérer la plupart des images. Je bosse toujours sur l'import global des catégories, livres et auteurs. L'actualité viendra plus tard, dans la mesure ou d'autres choses sont à faire avant.

**Comment by npeltier** [comment]
ok, je viens de transférer le contenu sur le site, on peut déclarer ce bug clos
