### ISSUE TITLE
Lancer l'hébergement du site

### ISSUE THREAD

**Issue by editions-barzakh** [editions-barzakh/site#3]

**Comment by editions-barzakh** [comment]
on regarde chez gandi pour l'instant, le small (https://www.gandi.net/hebergement/simple?language=nodejs) parait bien (basé sur 30k visites par mois, 2Mo par visite), il faudrait toutefois se renseigner sur les conditions de dépassement de traffic

**Comment by npeltier** [comment]
fait (mail à venir)
