### ISSUE TITLE
Créer un compte google analytics

### ISSUE THREAD

**Issue by editions-barzakh** [editions-barzakh/site#4]
dépend de #3

**Comment by npeltier** [comment]
@editions-barzakh pouvez-vous créer un compte (nouvelle adresse gmail dédiée), c'est gratuit ? et m'envoyer par les moyens habituels login/mot de passe?

https://support.google.com/analytics/answer/1008015

**Comment by editions-barzakh** [comment]
@npeltier Compte google analytics crée. je t'envoie les informations par message.
