### ISSUE TITLE
taille images

### ISSUE THREAD

**Issue by editions-barzakh** [editions-barzakh/site#45]
@npeltier Peut-on mettre une taille et un format standard pour les images auteurs et actualité ?

**Comment by npeltier** [comment]
@editions-barzakh malheureusement non, je les redimenssionne pour qu'elles aient toutes exactement la même largeur, mais dès que le ratio largeur/hauteur change, ça ne fonctionne plus. Je ne peux pas non plus changer ce ratio, ou sinon les images seraient déformées. 
Ca fonctionne bien pour les livres, pour les auteurs et actu, au cas par cas, il faudrait mettres des photos toute en mode portrait ou paysage (l'important c'est l'unité).
