### ISSUE TITLE
Lettrines

### ISSUE THREAD

**Issue by editions-barzakh** [editions-barzakh/site#47]
@npeltier Peut-on éviter les lettrines ? et avoir plus de choix dans le style des textes.

**Comment by npeltier** [comment]
@editions-barzakh Je peux les retirer oui, par contre pour le style de texte je découragerais clairement car ça nuit à la consistence visuelle, c'est déjà fait à certains endroits (je pense des copiers coller depuis Word). 
Si le style actuel ne vous plait pas, on peut le changer, mais je pense qu'il faudrait le même partout.

**Comment by editions-barzakh** [comment]
d'accord pour le style actuel sans lettrine. je travaille à harmoniser tous les textes.
