### ISSUE TITLE
redirection .dz -> .com

### ISSUE THREAD

**Issue by npeltier** [editions-barzakh/site#49]
Il faudrait rendre effective la redirection permantente de .dz vers .com

**Comment by editions-barzakh** [comment]
enfin obtenu la redirection ! http://www.editions-barzakh.com/

**Comment by npeltier** [comment]
@editions-barzakh pouvez vous demander également les redirections permanentes des adresses figurant encore sur la première page de résultat de
https://www.google.fr/?q=editions+barzakh ?
(à défaut de la clôture du site, bien sûr)
